services:
  - type: web
    name: trading-bot
    env: docker
    plan: free
    autoDeploy: true
    branch: main
    healthCheckPath: /
    envVars:
      - key: LOG_LEVEL
        value: INFO
      - key: PORT
        value: 8000

  - type: worker
    name: trading-bot-worker
    env: docker
    plan: free
    autoDeploy: true
    branch: main
    dockerCommand: python run_worker.py
    envVars:
      - key: PAPER
        value: "true"
      - key: TICKER
        value: "AAPL"
      - key: PERIOD
        value: "1mo"
      - key: INTERVAL
        value: "30m"
      - key: POLL_INTERVAL
        value: "15"
      - key: EQUITY
        value: "10000"
      - key: RISK_PCT
        value: "0.01"
      - key: LOG_LEVEL
        value: "INFO"
      - key: RSI_BUY
        value: "55"
      - key: RSI_SELL
        value: "45"
      - key: MACD_HIST_BUY
        value: "0.0"
      - key: MACD_HIST_SELL
        value: "0.0"
      - key: MIN_SCORE
        value: "0.0"