# ============================
# Render Deployment Blueprint
# ============================

services:
  # --- Public Web API (FastAPI) ---
  - type: web
    name: trading-bot
    env: docker
    plan: free                 # נשאר בחינם ל־API
    autoDeploy: true
    branch: main
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: LOG_LEVEL
        value: info
      - key: PORT
        value: 8000

  # --- Background Worker (24/7) ---
  - type: worker
    name: trading-bot-worker
    env: docker
    plan: starter              # נדרש Worker בתשלום (Starter $7/חודש)
    autoDeploy: true
    branch: main
    # מריץ את הסקריפט של הלופר
    startCommand: python run_worker.py

    # ברירות מחדל בטוחות — אפשר לשנות בהמשך ממשק Render או פה
    envVars:
      - key: PAPER
        value: "true"          # מסחר על נייר בלבד
      - key: TICKER
        value: AAPL
      - key: PERIOD
        value: 1mo
      - key: INTERVAL
        value: 30m
      - key: POLL_INTERVAL
        value: "30"
      - key: EQUITY
        value: "10000"
      - key: RISK_PCT
        value: "0.01"
      - key: LOG_LEVEL
        value: info